version: '3.8'

services:
  url-shortener:
    build:
      context: src
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  redis:
    image: ghcr.io/microsoft/garnet:latest
    ports:
      - "6379:6379"
